#!/bin/bash

clear


read -p "Enter your region: " REGION
gcloud config set compute/zone "$REGION"

export PROJECT_ID=$(gcloud info --format='value(config.project)')

gcloud container clusters get-credentials central --zone "$REGION"

git clone https://github.com/xiangshen-dk/microservices-demo.git
cd microservices-demo || exit

kubectl apply -f release/kubernetes-manifests.yaml

sleep 30

gcloud logging metrics create Error_Rate_SLI \
  --description="Error rate for recommendationservice" \
  --log-filter='resource.type="k8s_container" severity=ERROR labels."k8s-pod/app": "recommendationservice"'

sleep 30

cat > awesome.json <<EOF
{
  "displayName": "Error Rate SLI",
  "userLabels": {},
  "conditions": [
    {
      "displayName": "Kubernetes Container - logging/user/Error_Rate_SLI",
      "conditionThreshold": {
        "filter": "resource.type = \"k8s_container\" AND metric.type = \"logging.googleapis.com/user/Error_Rate_SLI\"",
        "aggregations": [
          {
            "alignmentPeriod": "300s",
            "crossSeriesReducer": "REDUCE_NONE",
            "perSeriesAligner": "ALIGN_RATE"
          }
        ],
        "comparison": "COMPARISON_GT",
        "duration": "0s",
        "trigger": {
          "count": 1
        },
        "thresholdValue": 0.5
      }
    }
  ],
  "alertStrategy": {
    "autoClose": "604800s"
  },
  "combiner": "OR",
  "enabled": true,
  "notificationChannels": [],
  "severity": "SEVERITY_UNSPECIFIED"
}
EOF

gcloud alpha monitoring policies create --policy-from-file="awesome.json"

echo
echo "======================================================="
echo "              LAB COMPLETED SUCCESSFULLY!              "
echo "======================================================="
echo
echo "YouTube: https://www.youtube.com/@ansanjohny653/videos"
echo "Don't forget to Like, Share and Subscribe for more videos!"
echo
